require("user.alpha")
require("user.autocommands")
require("user.autopairs")
require("user.bufferline")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.gitsigns")
require("user.hot-reload")
require("user.impatient")
require("user.indentline")
require("user.keymaps")
require("user.lsp")
require("user.lualine")
require("user.notify")
require("user.nvim-tree")
require("user.options")
require("user.plugins")
require("user.project")
require("user.telescope")
require("user.treesitter")
require("user.whichkey")

-- :%s/.*\n/\0\r/g double space file
